export const mainTypes = {
	GET_ABOUT_DATA: "GET_ABOUT_DATA",
	GET_CAROUSEL_DATA: "GET_CAROUSEL_DATA",
	GET_COLLAPSE_ITEMS: "GET_COLLAPSE_ITEMS",
	GET_COUNTRIES: "GET_COUNTRIES",
	GET_DOG: "GET_DOG",
	GET_POINTS: "GET_POINTS",
	GET_MAP_POINTS: "GET_MAP_POINTS",
	ADD_VIDEO: "ADD_VIDEO",
	DELETE_VIDEO: "DELETE_VIDEO",
};
